export default {
  'full-width-profile': 'Full Width Profile',
  'profile-card': 'Profile Card',
  'profile-tooltip': 'Profile Tooltip',
  'profile-list': 'Profile List',
  'profile-list-row': 'Profile List Row',
  'profile-stats': 'Profile Stats',
  'profile-socials': 'Profile Socials',
  avatar: 'Avatar',
  'follower-tag': 'Follower Tag',
  'followers-you-know': 'Followers you know',
  'followers-and-following': 'Followers and Following',
  'follow-button': 'Follow Button',
  'transaction-modal': 'Transaction Modal',
  'transaction-provider': 'Transaction Provider',
  notifications: 'Notifications',
  'siwe-button': 'SIWE Button',
  'translation-provider': 'Translation Provider',
}
